### ISSUE TITLE
App Store clone

### ISSUE THREAD

**Issue by QuetzalPretzel** [BenziAhamed/Nevergrid#1]
I’m sorry to report that your app has been cloned :-(

See here: https://itunes.apple.com/us/app/blob-grid/id1095145518?mt=8

He’s a serial cloner, see here: https://itunes.apple.com/us/developer/daniel-dugan/id860196910 all these are clones, e.g. “Banana Ape” = “Banana Catcher”. He trawls GitHub for apps to steal.

Good news, you can get his app pulled by contacting Apple Legal here:

http://www.apple.com/legal/internet-services/itunes/appstorenotices/

Let me know if you need any advice on submitting the claim, it helps to include your app id in the text and add that you icon has also been infringed (don’t be afraid to write lots even though the text entry box is tiny).

**Comment by QuetzalPretzel** [comment]
BTW, it does' t matter what your licence is, there are no modifications, identical code, identical icon, identical app, you have full grounds to issue a take down request. Developers should not do that in the App Store regardless of the open source licence.

**Comment by BenziAhamed** [comment]
Oh wow, it didn't even take that long! Thanks for letting me know. I will contact Apple Legal.
